export const FETCH_PRODUCTS_REQUESTED = 'FETCH_PRODUCTS_REQUESTED'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'
export const SET_FILTERED_PRODUCTS = 'SET_FILTERED_PRODUCTS'
